

--36
select MASP , sum(SL) as SL from HOADON JOIN CTHD on HOADON.SOHD = CTHD.SOHD
where month (NGHD) = 10 AND year (NGHD) = 2006
group by MASP

--37
select MONTH(NGHD) as THANG , SUM(TRIGIA) as TONGDOANHTHU from HOADON
where YEAR(NGHD) = 2006
group by MONTH(NGHD)

--38
select SOHD from CTHD
GROUP BY SOHD
HAVING COUNT(DISTINCT MASP) > 3

--39
SELECT SOHD FROM CTHD JOIN SANPHAM ON CTHD.MASP = SANPHAM.MASP
WHERE NUOCSX ='Viet Nam'
GROUP BY SOHD
HAVING COUNT(DISTINCT CTHD.MASP) = 3

--40
SELECT TOP 1 KHACHHANG.MAKH
FROM HOADON JOIN KHACHHANG ON HOADON.MAKH = KHACHHANG.MAKH
GROUP BY KHACHHANG.MAKH , HOTEN
ORDER BY COUNT(*) DESC

--41
SELECT TOP 1 MONTH(NGHD) AS THANG FROM HOADON
WHERE YEAR(NGHD) = 2006
GROUP BY MONTH(NGHD)
ORDER BY SUM(TRIGIA) DESC

--42
SELECT MASP FROM HOADON JOIN CTHD ON HOADON.SOHD = CTHD.SOHD
WHERE YEAR (NGHD) = 2006
GROUP BY MASP
ORDER BY SUM(SL) ASC

--43
SELECT NUOCSX , MASP , TENSP 
FROM SANPHAM
GROUP BY NUOCSX , MASP ,TENSP 
ORDER BY MAX(GIA) DESC

--44
SELECT NUOCSX FROM SANPHAM
GROUP BY NUOCSX
HAVING COUNT(DISTINCT GIA) > 2

--45
SELECT TOP 1 MAKH ,HOTEN 
FROM (
		SELECT TOP 10 KHACHHANG.MAKH , KHACHHANG.HOTEN , COUNT(HOADON.MAKH) AS SL
		FROM  KHACHHANG JOIN HOADON ON KHACHHANG.MAKH = HOADON.MAKH
		GROUP BY KHACHHANG.MAKH , KHACHHANG.DOANHSO , KHACHHANG.HOTEN
		ORDER BY KHACHHANG.DOANHSO DESC
		) KH
ORDER BY SL DESC